version: '3.3'

networks:
    laravel:
        driver: bridge

services:
    workspace81:
        build:
            context: ./
            dockerfile: Dockerfile81
        image: laravel81
        container_name: workspace81
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            -   ./src:/var/www/
        networks:
            - laravel

    workspace74:
        build:
            context: ./
            dockerfile: Dockerfile74
        image: laravel74
        container_name: workspace74
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            -   ./src:/var/www/
        networks:
            - laravel

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www
            - ./nginx:/etc/nginx/conf.d
        networks:
            - laravel
        depends_on:
            -   workspace81
            -   workspace74

    mariadb:
        image: mariadb:10.6.4-focal
        container_name: mariadb
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mariadb
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - laravel
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8001:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariadb
        networks:
            - laravel
        depends_on:
            - mariadb