version: '3.3'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - /home/oxicuza/Productions/docker/src:/var/www
            - /home/oxicuza/Productions/docker/nginx/conf:/etc/nginx/conf.d
        networks:
            - app-network

networks:
    app-network:
        driver: bridge