version: '3.3'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - absolute-path-src:/var/www
            - absolute-path-conf:/etc/nginx/conf.d
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    absolute-path-src:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/oxicuza/Productions/docker/src
    absolute-path-conf:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/oxicuza/Productions/docker/nginx/conf