version: '3.3'

services:
    mariadb:
        image: mariadb:10.6.4-focal
        container_name: mariadb
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
        ports:
            - "3306:3306"
        volumes:
            - /home/oxicuza/Productions/docker/mariadb/data:/var/lib/mysql:rw
        networks:
            - app-network

networks:
    app-network:
        driver: bridge